// flow-typed signature: a4eb54e80d1e902eaeb43425e827459a
// flow-typed version: <<STUB>>/graphql-server-express_v^0.7.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-server-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-server-express' {
  declare module.exports: any;
}
