export default [
  {name: 'CENTIMETERS', abbr: 'cm.'},
  {name: 'CUPS', abbr: 'c.'},
  {name: 'DESSERT_SPOONS', abbr: 'dessert spoons'},
  {name: 'FEET', abbr: 'ft.'},
  {name: 'FLUID_OUNCES', abbr: 'fl oz.'},
  {name: 'GALLONS', abbr: 'ga.'},
  {name: 'GRAMS', abbr: 'g.'},
  {name: 'INCHES', abbr: 'in.'},
  {name: 'KILOGRAMS', abbr: 'kg.'},
  {name: 'KILOMETERS', abbr: 'km.'},
  {name: 'LITERS', abbr: 'l.'},
  {name: 'METERS', abbr: 'm.'},
  {name: 'MILES', abbr: 'mi.'},
  {name: 'MILLIGRAMS', abbr: 'mg.'},
  {name: 'MILLILITERS', abbr: 'mL.'},
  {name: 'MILLIMETERS', abbr: 'mm.'},
  {name: 'OUNCES', abbr: 'oz.'},
  {name: 'PINTS', abbr: 'pts.'},
  {name: 'POUNDS', abbr: 'lbs.'},
  {name: 'QUARTS', abbr: 'qts.'},
  {name: 'TABLESPOONS', abbr: 'tbsp.'},
  {name: 'TEASPOONS', abbr: 'tsp.'},
  {name: 'UNITLESS', abbr: ''},
  {name: 'YARDS', abbr: 'yds.'}
]
